name: Build Templates Website

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message for this website deploy'
        required: true
        default: 'Update templates website'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: danfickle/openhtmltopdf
          path: openhtmltopdf
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile with Maven
        run: cd openhtmltopdf && mvn -B install -DskipTests && cd ..
      - name: Build website
        run: cd openhtmltopdf/openhtmltopdf-templates && mvn -B exec:java -Dexec.mainClass="com.openhtmltopdf.templates.Application" && cd ../..
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./openhtmltopdf/openhtmltopdf-templates/target/website/pdfs
          commit_message: ${{ github.event.inputs.message }}
